name: Build HTML Docs
on:
  push:
    branches:
      - docs
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
defaults:
  run:
    shell: bash --login -ieo pipefail {0}
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout Build Files
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false
          ref: docs
      - name: Checkout OpenCorePkg Master
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false
          repository: acidanthera/OpenCorePkg
          path: master
      - name: Get Latest OpenCorePkg Release
        uses: oprypin/find-latest-tag@v1
        with:
          repository: acidanthera/OpenCorePkg
          releases-only: true
        id: releasetag
      - run: echo "Latest release is ${{ steps.releasetag.outputs.tag }}"
      - name: Checkout OpenCorePkg Release
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false
          repository: acidanthera/OpenCorePkg
          path: release
          ref: ${{ steps.releasetag.outputs.tag }}
      - name: Get Latest MacTeX Version
        id: mactexversion
        run: |
          echo "::set-output name=version::$(brew cask info mactex | head -1 | cut -c 9-)"
      - name: Cache Brew Downloads
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/downloads/*mactex*
            ~/Library/Caches/Homebrew/downloads/*ghostscript*
            ~/Library/Caches/Homebrew/*ghostscript*
          key: ${{ runner.os }}-mactex-${{ steps.mactexversion.outputs.version }}
      - name: Install Dependencies
        run: |
          brew cask install mactex
      - name: Refresh PATH
        run: eval "$(/usr/libexec/path_helper)"
      - name: Build Master Configuration
        run: |
          cd master/Docs
          ./BuildDocs.tool
          make4ht Configuration.tex
      - name: Build Master Differences
        run: |
          cd master/Docs/Differences
          make4ht Differences.tex
      - name: Build Master Errata
        run: |
          cd master/Docs/Errata
          make4ht Errata.tex
      - name: Build Release Configuration
        run: |
          cd release/Docs
          ./BuildDocs.tool
          make4ht Configuration.tex
      - name: Build Release Differences
        run: |
          cd release/Docs/Differences
          make4ht Differences.tex
      - name: Build Release Errata
        # Errata not in 0.5.9 yet, ignore failure
        run: |
          if [ -d "release/Docs/Errata" ]; then
          cd release/Docs/Errata
          make4ht Errata.tex
          fi
      - name: Copy Files
        run: |
          mkdir -p Deploy/master Deploy/release
          cp -R master/Docs/*.css master/Docs/*.html master/Docs/*.png master/Docs/Differences/*.css master/Docs/Differences/*.html master/Docs/Differences/*.png master/Docs/Errata/*.css master/Docs/Errata/*.html master/Docs/Errata/*.png master/Docs/Logos Deploy/master/ || true
          cp -R release/Docs/*.css release/Docs/*.html release/Docs/*.png release/Docs/Differences/*.css release/Docs/Differences/*.html release/Docs/Differences/*.png release/Docs/Errata/*.css release/Docs/Errata/*.html release/Docs/Errata/*.png release/Docs/Logos Deploy/release/ || true
          cp Copy/Differences.css Deploy/master/
          cp Copy/Differences.css Deploy/release/
          cp Copy/index.html Deploy/
          echo
          ls Deploy
      - name: Post Build
        run: python3 postbuild.py ${{ steps.releasetag.outputs.tag }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: Deploy
          TARGET_FOLDER: docs
          BASE_BRANCH: master
          CLEAN: true
