name: Copy Website Files
on:
  push:
    branches:
      - blog
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build Files
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: .